import fs from "fs-extra";
import path from "node:path";
import type { ProjectContext } from "./scanner.js";

export async function generateProjectDocs(cwd: string, ctx: ProjectContext): Promise<void> {
  const docsDir = path.join(cwd, "docs");
  const adrDir = path.join(docsDir, "adr");
  await fs.ensureDir(docsDir);
  await fs.ensureDir(adrDir);

  // 1. docs/ARCHITECTURE.md
  let archTable = "";
  if (ctx.isMonorepo && (ctx.frontend || ctx.backend)) {
    archTable = `| Sub-Application | Path | Framework / Stack | Type |
| :--- | :--- | :--- | :---: |
| **Frontend** | \`${ctx.frontend?.path || "frontend"}\` | ${ctx.frontend?.framework || "Web UI"} | Client |
| **Backend** | \`${ctx.backend?.path || "backend"}\` | ${ctx.backend?.framework || "Server / API"} | Service |
| **Database** | - | ${ctx.database || "None"} | Storage |
| **Package Manager** | - | ${ctx.packageManager || "npm"} | Tooling |`;
  } else {
    archTable = `| Layer | Technology | Status |
| :--- | :--- | :---: |
| **Framework** | ${ctx.framework || "Custom"} | Active |
| **Language** | ${ctx.hasTypeScript ? "TypeScript" : "JavaScript"} | Active |
| **Database / ORM** | ${ctx.database || "Not detected"} | Active |
| **Package Manager** | ${ctx.packageManager || "npm"} | Active |`;
  }

  const archContent = `# 🏛️ System Architecture: ${ctx.name}

> Auto-generated by \`skilld-ai\` CLI based on project scan.

---

## 1. Overview & Tech Stack

${archTable}

---

## 2. High-Level Architecture Diagram

\`\`\`mermaid
flowchart TD
    Client["Client (Web / Mobile)"] --> Frontend["Frontend App (${ctx.frontend?.framework || ctx.framework || "Frontend"})"]
    Frontend --> Backend["Backend Service (${ctx.backend?.framework || "Backend API"})"]
    Backend --> Data["Storage / DB (${ctx.database || "Database"})"]
\`\`\`
`;
  await fs.writeFile(path.join(docsDir, "ARCHITECTURE.md"), archContent, "utf-8");

  // 2. docs/API_SPEC.md
  const apiContent = `# 📋 API Specification (Data Contracts)

> Single Source of Truth สำหรับ API Contract ระหว่าง Frontend (\`/dvf\`) และ Backend (\`/dvb\`)

---

## 1. Endpoints Directory

| Method | Endpoint | Description | Auth Required | Status |
| :---: | :--- | :--- | :---: | :---: |
| \`GET\` | \`/healthz\` | Health check liveness probe | No | \`Active\` |
| \`GET\` | \`/readyz\` | Readiness probe | No | \`Active\` |
`;
  await fs.writeFile(path.join(docsDir, "API_SPEC.md"), apiContent, "utf-8");

  // 3. docs/TASK_LIST.md
  const taskContent = `# 📌 Task List & Progress Tracking

> บันทึกรายการงานย่อย (Sub-tasks) สถานะ และผู้รับผิดชอบ ควบคุมโดย \`/dev\`

---

## 1. Active Sprint / Phase

| # | Task | Assignee | Target File / Area | Quality Gate | Status |
| :-: | :--- | :---: | :--- | :---: | :---: |
| 1 | Initial setup & Agent onboarding | \`/dev\` | \`AGENTS.md\`, \`.agents/\` | \`Gate 1-5\` | ✅ Completed |

---

## 2. Completed Tasks Archive

| # | Task | Completed By | Completion Date |
| :-: | :--- | :---: | :---: |
| 1 | AI Team Constitution Setup | \`skilld\` | ${new Date().toISOString().split("T")[0]} |
`;
  await fs.writeFile(path.join(docsDir, "TASK_LIST.md"), taskContent, "utf-8");

  // 4. docs/CODING_STANDARDS.md
  const standardsContent = `# 📏 Coding Standards & Conventions: ${ctx.name}

> ข้อตกลงร่วมในการเขียนโค้ด การตั้งชื่อ และโครงสร้างไฟล์

---

## 1. General Principles

| Principle | Rule |
| :--- | :--- |
| **No \`any\`** | ห้ามใช้ \`any\` เด็ดขาด ต้องกำหนด Type ชัดเจน |
| **Fail Fast** | Validate ข้อมูลตั้งแต่ต้นทาง (Input/Payload) ด้วย Schema Library |
| **4 UI States** | หน้าจอ/Component ที่ต่อ API ต้องมีครบ Loading, Empty, Error, Success |
`;
  await fs.writeFile(path.join(docsDir, "CODING_STANDARDS.md"), standardsContent, "utf-8");
}
